### ISSUE TITLE
Animation picture not working

### ISSUE THREAD

**Issue by beautylix** [hypeJunction/ckeditor_addons#1]
When I uploaded a animated gif picture, it did not animate, I checked and found that you changed the file extension, and hashed the filename.

Hashed filename is too long and not friendly for SEO, and without the extension, the animated gif pictures will not work.

**Comment by hypeJunction** [comment]
The plugin resizes all images and saves them as JPEG. Elgg can't currently handle resizing of GIFs. hypeApps can handle resizing of gifs (I believe WideImage used for resizing can handle multiple frames). I suppose the easiest is to leave GIFs alone, but I honestly don't care enough about this to invest time into it. Feel free to send a pull request if you come up with a solution.

**Comment by beautylix** [comment]
It is unnecessary to resize the image, because the system automatically resized the image when you uploaded. in other words, the maximum width of image equals width of content area.

As you know, many many people like to upload GIF animated pictures to social network, and I think the feature is required.

**Comment by hypeJunction** [comment]
Required or not, I don't have time for it, so feel free to submit a pull request.

**Comment by hypeJunction** [comment]
Consider someone uploading 10 different images 4-5Mb each with really high dpi. Sure, the images will fit the container, but how much time will take for the images to load? How much space is that going to occupy on the server? Are you really sure what's been uploaded is an image? Resizing images is the key to performance and security.

**Comment by beautylix** [comment]
Animated GIF is a part of social network, I think its priority is higher than performance, now bandwidth is not expensive, as for security, resize is a method, another one is to convert the image into binary file, and find the end flag, and delete the data attached after the flag signal

Actually I did not understand your code well, especially browse.php, I did not figure out why only invoking resize function can work, and when I invoked other function, it did not work.

Drag and upload feature is very cool;, but the file name encrypted with md5 is too long, sometimes over 20 HEX symbols.
