### ISSUE TITLE
Feature Request for After the Deadline plugin

### ISSUE THREAD

**Issue by dipenpatel235** [hypeJunction/ckeditor_addons#12]
After the Deadline plugin for CKEditor.

i want to add Grammer check using ckeditor.
so can u please help me to how to add this plugin inside your ckeditor plugin ?
Thanks

**Comment by hypeJunction** [comment]
Implement it as an independent plugin using `'prepare','ckeditor'` javascript hook.
http://learn.elgg.org/en/stable/guides/javascript.html?highlight=ckeditor#module-elgg-ckeditor
