### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by beautylix** [hypeJunction/ckeditor_addons#3]
Please add Blockquote and Textarea to the addon, thanks a lot

**Comment by hypeJunction** [comment]
Blockquote is there - enable in plugin settings.
Not sure what Textarea means.

**Comment by beautylix** [comment]
`<textarea>` 
`content` 
`</textarea>`

It  is used to insert a block of codes or scripts

`<blockquote>`
`content`
`</blockquote>`

It is used to quote something, its symbol is double quote.

They are both HTML tags

**Comment by beautylix** [comment]
Blockquote is a feature of Quote, its symbol is double quote.

**Comment by hypeJunction** [comment]
It is not. `<textarea>` is plaintext input, which CKEditor transforms into WYSIWYG. For code you should be using `<pre>` or `<code>`. 
Double quote is not a feature of a `<blockquote>`. You can style blockquote with CSS to display double quotes.
I suggest you read up on HTML elements: https://developer.mozilla.org/en-US/docs/Web/HTML/Element

At this time I will not be adding any more new features. There are hooks to extend the functionality with custom addons.
