### ISSUE TITLE
Image upload causes the entity guid in URL not increasing correctly

### ISSUE THREAD

**Issue by beautylix** [hypeJunction/ckeditor_addons#4]
In the addon, each uploaded image got an entity guid, and that cause the entity guid in URL not consistent.

For example, your last blog URL is domain.com/blog/view/70/friendly-title, if you write a new blog post at once, the URL should have been domain.com/blog/view/71/friendly-title, However, with the ckeditor addon, if you uploaded 10 images to server, and the blog URL would be domain.com/blog/view/81/friendly-title

I do think it is not friendly for SEO,  hope you review and fix it, thanks a lot

**Comment by hypeJunction** [comment]
I don't understand the problem.

**Comment by beautylix** [comment]
Take blog as an example, the URL of blog post is as blog/view/{$entity->guid}/$friendly_title, $entity->guid will show a number in URL, and normally the number will auto increment if you add new entity.

However, if you used the addon, after you uploaded images to server, your $entity->guid in URL will add more than 1, in other words , it does not increment. for example. Given your previous URL is domain/view/100/friendly-title, if you uploaded 1 image to your blog post,  when you publish the current blog post, the shown URL is domain/view/102/friendly-title,; if you uploaded 20 images, when you publish the blog post, the shown URL is domain/view/121/friendly-title, but the correct URL should have been domain/view/101/friendly-title. actually the addon assigned each uploaded image a $entity->guid, and so that $entity->guid in URL is not consistent.

Do you understand what I mean?

**Comment by hypeJunction** [comment]
Images are entities with incremented guid. You would have to save the blog before uploading images to get the guid you want.
