### ISSUE TITLE
Image upload not really working

### ISSUE THREAD

**Issue by iionly** [hypeJunction/ckeditor_addons#7]
A discussion on the community site brought it up (https://elgg.org/discussion/view/2621453). As far as I could test it so far:

- it works immediatelly after resetting the cache (for admin) in the same login session,
- it doesn't work anymore (for admins) after logging out and logging in again,
- it never works for normal users.

Maybe two issues actually. One issue (for normal users) might be the creation of the ckeditor folder in their data directory on the first image upload. At least there are some errors in the log ("opendir(/home/xxx/ckeditor/assets): failed to open dir: No such file or directory").

The other might be some race condition with module dependencies. Unfortunately, I don't see any errors in the log or console.

Tested with release 5.0.0 on Elgg 2.3.1 both with and without hypeScraper (without hypeScraper I get an error in the console about some wikplayer stuff missing but I think that's unrelated to this issue).

**Comment by iionly** [comment]
Okay. Understood now that I need to create the ckeditor/assets folder in dataroot manually to allow for uploading of static stuff (admin only). Not sure if uploading non-static stuff is supposed to be admin only, too, or if this part is at least not working as intended atm.

**Comment by iionly** [comment]
Maybe once more some issue with caching+ckeditor. Upload works both for admin+normal user with caching disabled. With caching enabled it fails. Don't know if it's the action token that causes the problem. If I set filebrowserUploadUrl directly in the hook handler, it works also with caching enabled:
```
		// Apply custom config
		elgg.register_hook_handler('config', 'ckeditor', function (hook, type, params, config) {
			config = config || {};
			var custom = <?php echo json_encode($config) ?>;

			custom.toolbar = elgg.is_admin_logged_in() ? <?php echo json_encode($admin_toolbar) ?> : <?php echo json_encode($user_toolbar) ?>;

			custom.filebrowserBrowseUrl = elgg.get_site_url() + "ckeditor/browse";
			custom.filebrowserUploadUrl = elgg.security.addToken(elgg.get_site_url() + "action/ckeditor/upload");
			custom.filebrowserImageWindowWidth = '640';
			custom.filebrowserImageWindowHeight = '480';

			return $.extend({}, config, custom);
		});
```

**Comment by hypeJunction** [comment]
Feel free to make a PR. I won't get to this for a while.

**Comment by iionly** [comment]
Done: https://github.com/hypeJunction/Elgg-ckeditor_addons/pull/8

**Comment by hypeJunction** [comment]
Thanks
